import React, { Component } from "react";
import { Text, Image, View, StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
    // shapes
    CircleShapeOne: {
        width: 180,
        height: 180,
        borderRadius: 180 / 2,
        backgroundColor: "#0080A9",
        opacity: 0.5,
        marginTop: -30,
        marginRight: -200,
    },
    CircleShapeTwo: {
        width: 280,
        height: 280,
        borderRadius: 280 / 2,
        backgroundColor: "#0080A9",
        opacity: 0.5,
        marginTop: -50,
        marginRight: -60,
    },
    CircleShapeThree: {
        width: 400,
        height: 400,
        borderRadius: 400 / 2,
        backgroundColor: "#0080A9",
        opacity: 0.5,
        marginTop: -280,
        marginRight: 175,
    },
    // All css
    container: {
        flex: 1,
        backgroundColor: "#EEEEEE",
        alignItems: "center",
        // paddingTop: 200,
        // fontFamily: "Montserrat",
    },
    linearGradient: {
        width: "100%",
        height: "100%",
        // height: "auto",
        opacity: 0.95,
        justifyContent: "center",
        alignItems: "center",
    },
    btnbox: {
        width: 320,
        height: 50,
        // backgroundColor: "#F5D328",
        borderRadius: 5,
        marginTop: 50,
        elevation: 5,
        alignItems: "center",
        justifyContent: "center",
        // padding: 17,
        // shadowColor: "#000",
        // shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.8,
        // shadowRadius: 2,
        // alignContent: "center",
    },
    heading: {
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 60,
        // paddingTop: -250,
        marginTop: -300,
        color: "#FFF",
    },

    // splash screen css
    // text: {
    //     color: "#fff",
    //     fontSize: 40,
    //     fontWeight: "bold",
    //     textAlign: "center",
    // },

    // registration Screen css
    inputbox: {
        width: "80%",
        height: 40,
        backgroundColor: "#FFF",
        // paddingLeft: 20,
        // paddingRight: 40,
        color: "#000",
        fontSize: 13,
        // borderRadius: 5,
        // marginTop: 15,
        // marginBottom: 50,
        // borderColor: "#8CF1E7",
        // borderStyle: "solid",
        // borderWidth: 1,
        // flexDirection: "row",
        // // justifyContent: "center",
        // alignContent: "center",
        // alignItems: "center",
        // flexDirection: "row",
        // justifyContent: "center",
        // alignContent: "center",
        // alignItems: "center",
    },
    btntext: {
        color: "#FFF",
        fontSize: 20,
        fontWeight: "bold",
    },

    textLink: {
        color: "#000",
        fontSize: 15,
        textAlign: "center",
        paddingTop: 12,
    },
    span: {
        color: "#00FFE6",
        fontWeight: "bold",
    },

    /// login css
    forgotText: {
        color: "#00FFE6",
        fontSize: 15,
        // textAlign: "right",
        paddingRight: 40,
        alignSelf: "flex-end",
    },

    //home screen css
    homeHeader: {
        // height: 200,
        // width: 450,
        // marginTop: 0,
        // padding: 0,
        textAlign: "center",
        fontSize: 15,
        color: "white",
        width: "100%",
        height: "auto",
        paddingTop: 30,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 5,
        marginBottom: 10,
        opacity: 0.95,
        justifyContent: "center",
        alignItems: "center",
    },
    searchBox: {
        // width: "100%",
        height: 50,
        backgroundColor: "#FFF",
        paddingLeft: 15,
        paddingRight: 10,
        margin: 10,
        color: "#000",
        fontSize: 20,
        borderRadius: 5,
        borderColor: "#8CF1E7",
        borderStyle: "solid",
        borderWidth: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignContent: "center",
        alignItems: "center",
    },
    homeContentBox: {
        height: 200,
        // width: 200,
        width: 195,
        margin: 5,

        color: "#000",
        fontSize: 15,
        fontWeight: "bold",
        borderRadius: 5,
        borderColor: "#8CF1E7",
        borderStyle: "solid",
        borderWidth: 1,
        textAlign: "center",
        alignContent: "center",
        justifyContent: "center",
    },
    profile: {
        paddingRight: 10,
        paddingTop: 40,
        paddingBottom: 30,
        margin: 10,
        // color: "#3B5998",
        // fontSize: 20,
        // flexDirection: "row",
        // justifyContent: "center",
        // alignContent: "center",
        alignItems: "center",
    },
    optionBox: {
        // height: 200,
        // width: 450,
        // marginTop: 0,
        // padding: 0,
        // textAlign: "center",
        fontSize: 15,
        // color: "white",
        width: "100%",
        height: 700,
        paddingTop: 10,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 5,
        marginBottom: 10,
        // opacity: 0.95,
        // flexDirection: "row",
        // justifyContent: "center",
        // alignContent: "center",
        // alignItems: "center",
    },
    profilebox: {
        // height: 200,
        // width: 450,
        // marginTop: 0,
        // padding: 0,
        // textAlign: "center",
        fontSize: 15,
        // color: "white",
        width: "100%",
        height: 700,
        paddingTop: 10,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 5,
        marginBottom: 10,
        // opacity: 0.95,
        // flexDirection: "row",
        // justifyContent: "center",
        // alignContent: "center",
        // alignItems: "center",
    },

    //category style
    listHeading: {
        fontSize: 20,
        fontWeight: "bold",
        // color: "#000",
        paddingTop: 50,
        paddingLeft: -50,
        marginLeft: -250,
        flexDirection: "row",
        // justifyContent: "center",
        // alignContent: "center",
        alignItems: "center",
    },
    listContentBox: {
        height: 100,
        width: "100%",
        // margin: 5,
        // paddingTop: 30,
        marginTop: 10,
        marginLeft: 30,
        color: "#000",
        fontSize: 15,
        fontWeight: "bold",
        borderRadius: 5,
        borderColor: "#8CF1E7",
        borderStyle: "solid",
        borderWidth: 1,
        alignItems: "center",
    },

    //purchase list
    purchaseContentBox: {
        height: 135,
        width: 400,
        // width: "100%",
        margin: 5,
        // marginLeft: -50,
        color: "#000",
        fontSize: 15,
        fontWeight: "bold",
        borderRadius: 5,
        borderColor: "#8CF1E7",
        borderStyle: "solid",
        borderWidth: 1,
        textAlign: "center",
        alignContent: "center",
        justifyContent: "center",
    },
});

export default styles;
